### ISSUE TITLE
EventHook handler - implement for DryRun message

### ISSUE THREAD

**Issue by kevinhillinger** [gpsuscodewith/azure-aap-deployment-driver#10]
- signal dryRunCompleted to the engine
- persist to the database

**Comment by tznamena** [comment]
As to the dry run it should be implemented as a regular deployment step (with a "step" and "execution" as any other step) that is invoked before the main loop starts. The rationale for this approach is that we can see result of the dry run in the UI as a normal step, including the errors.

**Comment by kevinhillinger** [comment]
@tznamena to ensure integration goes smoothly, what we're doing is creating dry run semantics explicitly, then once the results are received, the "step" will get updated as you mentioned.

**Comment by tznamena** [comment]
Sounds good, the dry run is a special case and needs to be hard coded to go first, before anything else. When we eventually get to run the whole deployment done from one template, rather than the individual templates, maybe the integration of dry run would be less of a special case.

**Comment by kevinhillinger** [comment]
@tznamena the "hard coded" step for the dry run is there now in engine/starter.go. We'll do a PR for these once @bobjac is done with dry run execution.
